-- Server-controlled bootstrap for confirmed consumer accounts.
-- The caller supplies Cognito's opaque sub plus UUID claims generated by the
-- registration Lambda. Email addresses and passwords are never stored here.

create or replace function clinical_private.bootstrap_self_service_consumer(
  _person_id uuid,
  _organization_id uuid,
  _identity_subject text
)
returns table(person_id uuid, organization_id uuid)
language plpgsql security definer set search_path = '' as $$
declare
  _existing_person uuid;
begin
  if _identity_subject !~ '^[A-Za-z0-9:_-]{8,128}$' then
    raise exception using errcode = '22023', message = 'consumer_registration_invalid';
  end if;

  select i.person_id into _existing_person
    from clinical_core.identities i
   where i.identity_pool='consumer' and i.identity_subject=_identity_subject;
  if found and _existing_person <> _person_id then
    raise exception using errcode = '42501', message = 'consumer_registration_identity_conflict';
  end if;

  insert into clinical_core.organizations(id, synthetic_label)
  values (_organization_id, 'Self-service consumer account')
  on conflict(id) do nothing;

  insert into clinical_core.persons(id, synthetic_subject_key)
  values (
    _person_id,
    'syn_' || substring(pg_catalog.encode(public.digest(_identity_subject, 'sha256'), 'hex') from 1 for 48)
  ) on conflict(id) do nothing;

  insert into clinical_core.identities(
    person_id, identity_pool, identity_subject, synthetic_attested
  ) values (_person_id, 'consumer', _identity_subject, true)
  on conflict(identity_pool, identity_subject) do nothing;

  if not exists (
    select 1 from clinical_core.identities i
     where i.person_id=_person_id and i.identity_pool='consumer'
       and i.identity_subject=_identity_subject and i.synthetic_attested=true
       and i.status='active'
  ) then
    raise exception using errcode = '42501', message = 'consumer_registration_identity_conflict';
  end if;

  return query select _person_id, _organization_id;
end
$$;

revoke all on function clinical_private.bootstrap_self_service_consumer(uuid,uuid,text)
  from public;
grant execute on function clinical_private.bootstrap_self_service_consumer(uuid,uuid,text)
  to clinical_core_api;
