-- AWS-native governed program studio, enrollment, and progress review.
-- No program content is seeded and paid enrollment is fail-closed until an
-- approved payment workflow supplies durable paid-invoice evidence.

create table clinical_core.program_templates(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),name text not null,description text,archived_at timestamptz,created_by_person_id uuid not null references clinical_core.persons(id),created_at timestamptz not null default clock_timestamp(),unique(id,organization_id));
create table clinical_core.program_template_versions(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),template_id uuid not null,version integer not null,status text not null default 'draft' check(status in('draft','approved','published','superseded')),content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'),content_sha256 text check(content_sha256 is null or content_sha256~'^[0-9a-f]{64}$'),requires_practitioner_review boolean not null default true check(requires_practitioner_review=true),created_by_person_id uuid not null references clinical_core.persons(id),approved_by_person_id uuid references clinical_core.persons(id),approved_at timestamptz,published_at timestamptz,created_at timestamptz not null default clock_timestamp(),foreign key(template_id,organization_id) references clinical_core.program_templates(id,organization_id),unique(template_id,version),unique(id,organization_id),check(not(content ?| array['affiliateUrl','destinationUrl','discountCode','trackingCode'])));
create table clinical_core.programs(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),name text not null,status text not null default 'draft' check(status in('draft','active','archived')),active_version_id uuid,archived_at timestamptz,created_by_person_id uuid not null references clinical_core.persons(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(id,organization_id));
create table clinical_core.program_versions(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),program_id uuid not null,version integer not null,status text not null default 'draft' check(status in('draft','in_review','approved','published','returned','superseded')),content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'),content_sha256 text check(content_sha256 is null or content_sha256~'^[0-9a-f]{64}$'),revision integer not null default 1,review_note text,created_by_person_id uuid not null references clinical_core.persons(id),approved_by_person_id uuid references clinical_core.persons(id),submitted_at timestamptz,approved_at timestamptz,published_at timestamptz,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),foreign key(program_id,organization_id) references clinical_core.programs(id,organization_id),unique(program_id,version),unique(id,organization_id),check(not(content ?| array['affiliateUrl','destinationUrl','discountCode','trackingCode'])));
alter table clinical_core.programs add constraint programs_active_version_fk foreign key(active_version_id) references clinical_core.program_versions(id);
create table clinical_core.program_offers(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),program_id uuid not null references clinical_core.programs(id),name text not null,payment_mode text not null check(payment_mode in('complimentary','invoice_required')),price_cents integer not null check(price_cents>=0),currency text not null default 'usd',access_duration_days integer check(access_duration_days is null or access_duration_days>0),enrollment_open boolean not null default false,status text not null check(status in('draft','active','archived')),version integer not null default 1,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(id,organization_id));
create table clinical_core.program_enrollments(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),patient_record_id uuid not null references clinical_core.patient_records(id),program_id uuid not null references clinical_core.programs(id),program_version_id uuid not null references clinical_core.program_versions(id),offer_id uuid references clinical_core.program_offers(id),status text not null default 'pending' check(status in('pending','active','paused','completed','withdrawn')),version integer not null default 1,access_expires_at timestamptz,complimentary_reason_present boolean not null default false,enrolled_by_person_id uuid not null references clinical_core.persons(id),enrolled_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(id,organization_id));
create table clinical_core.program_progress(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),enrollment_id uuid not null references clinical_core.program_enrollments(id),lesson_id text,block_id text,kind text not null,payload jsonb not null check(jsonb_typeof(payload)='object'),needs_review boolean not null default false,review_state text not null default 'unreviewed' check(review_state in('unreviewed','reviewed','followup_required')),recorded_by_person_id uuid not null references clinical_core.persons(id),recorded_at timestamptz not null default clock_timestamp(),reviewed_by_person_id uuid references clinical_core.persons(id),reviewed_at timestamptz);
create table clinical_core.program_version_events(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),program_version_id uuid references clinical_core.program_versions(id),template_version_id uuid references clinical_core.program_template_versions(id),action text not null,safe_metadata jsonb not null default '{}'::jsonb,actor_person_id uuid not null references clinical_core.persons(id),occurred_at timestamptz not null default clock_timestamp(),check(jsonb_typeof(safe_metadata)='object' and not(safe_metadata ?| array['content','payload','note','reason'])));

do $$ declare _table text; begin foreach _table in array array['program_templates','program_template_versions','programs','program_versions','program_offers','program_enrollments','program_progress','program_version_events'] loop execute format('alter table clinical_core.%I enable row level security',_table); execute format('revoke all on clinical_core.%I from public,clinical_core_api',_table); end loop; end $$;
create trigger program_version_events_append_only before update or delete on clinical_core.program_version_events for each row execute function clinical_reference.reject_immutable_catalog_history();

create or replace function clinical_core.invoke_program_operation(_operation text,_args jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare _org uuid:=clinical_private.organization_id(); _actor uuid; _id uuid; _id2 uuid; _patient uuid; _version integer; _rows jsonb; _hash text; _program clinical_core.programs%rowtype; _pv clinical_core.program_versions%rowtype; _offer clinical_core.program_offers%rowtype; _enrollment clinical_core.program_enrollments%rowtype;
begin if _args is null or jsonb_typeof(_args)<>'object' or octet_length(_args::text)>1048576 then raise exception using errcode='22023',message='program_arguments_invalid'; end if; if _args ? '_organization_id' and (_args->>'_organization_id')::uuid<>_org then raise exception using errcode='42501',message='organization_context_mismatch'; end if; _actor:=clinical_private.require_knowledge_editor(_org);
  if _operation='list_program_templates' then select coalesce(jsonb_agg(to_jsonb(t) order by t.name),'[]'::jsonb) into _rows from clinical_core.program_templates t where organization_id=_org and ((_args->>'_include_archived')::boolean or archived_at is null); return _rows;
  elsif _operation='create_program_template' then insert into clinical_core.program_templates(organization_id,name,description,created_by_person_id) values(_org,btrim(_args->>'_name'),nullif(_args->>'_description',''),_actor) returning id into _id; insert into clinical_core.program_template_versions(organization_id,template_id,version,content,created_by_person_id) values(_org,_id,1,coalesce((select content from clinical_core.program_template_versions where id=nullif(_args->>'_from_version_id','')::uuid and organization_id=_org),'{}'::jsonb),_actor) returning id into _id2; return jsonb_build_object('templateId',_id,'versionId',_id2);
  elsif _operation='archive_program_template' then update clinical_core.program_templates set archived_at=case when (_args->>'_archived')::boolean then clock_timestamp() end where id=(_args->>'_template_id')::uuid and organization_id=_org returning id into _id; if not found then raise exception using errcode='P0002',message='program_template_not_found'; end if; return jsonb_build_object('ok',true);
  elsif _operation='approve_program_template_version' then update clinical_core.program_template_versions set status='approved',approved_by_person_id=_actor,approved_at=clock_timestamp(),content_sha256=encode(public.digest(convert_to(content::text,'UTF8'),'sha256'),'hex') where id=(_args->>'_version_id')::uuid and organization_id=_org and status='draft' returning id into _id; if not found then raise exception using errcode='40001',message='template_approval_refused'; end if; return jsonb_build_object('ok',true,'versionId',_id);
  elsif _operation='create_program' then insert into clinical_core.programs(organization_id,name,created_by_person_id) values(_org,btrim(_args->>'_name'),_actor) returning id into _id; insert into clinical_core.program_versions(organization_id,program_id,version,content,created_by_person_id) values(_org,_id,1,coalesce((select content from clinical_core.program_template_versions where template_id=nullif(_args->>'_from_template_id','')::uuid and organization_id=_org and status in('approved','published') order by version desc limit 1),'{}'::jsonb),_actor) returning id into _id2; return jsonb_build_object('programId',_id,'versionId',_id2);
  elsif _operation='list_programs' then select coalesce(jsonb_agg(to_jsonb(p) order by p.updated_at desc),'[]'::jsonb) into _rows from (select * from clinical_core.programs where organization_id=_org and (nullif(_args->>'_status','') is null or status=_args->>'_status') and (nullif(_args->>'_query','') is null or name ilike '%'||(_args->>'_query')||'%') order by updated_at desc limit least(coalesce((_args->>'_limit')::integer,100),500)) p; return _rows;
  elsif _operation='get_program_studio' then select * into _program from clinical_core.programs where id=(_args->>'_program_id')::uuid and organization_id=_org; if not found then raise exception using errcode='P0002',message='program_not_found'; end if; return jsonb_build_object('program',to_jsonb(_program),'versions',(select coalesce(jsonb_agg(to_jsonb(v) order by version desc),'[]'::jsonb) from clinical_core.program_versions v where program_id=_program.id));
  elsif _operation='save_program_draft' then _hash:=encode(public.digest(convert_to((_args->'_payload')::text,'UTF8'),'sha256'),'hex'); update clinical_core.program_versions set content=_args->'_payload',content_sha256=_hash,revision=revision+1,updated_at=clock_timestamp() where id=(_args->>'_version_id')::uuid and organization_id=_org and status in('draft','returned') and updated_at=(_args->>'_expected_updated_at')::timestamptz returning revision into _version; if not found then raise exception using errcode='40001',message='program_draft_conflict'; end if; return jsonb_build_object('ok',true,'revision',_version,'contentSha256',_hash);
  elsif _operation='submit_program_version' then update clinical_core.program_versions set status='in_review',submitted_at=clock_timestamp() where id=(_args->>'_version_id')::uuid and organization_id=_org and status in('draft','returned') and content_sha256 is not null returning id into _id; if not found then raise exception using errcode='40001',message='program_submit_refused'; end if; return jsonb_build_object('ok',true);
  elsif _operation in('approve_program_version','return_program_version') then if _operation='approve_program_version' and length(btrim(coalesce(_args->>'_note','')))<10 then raise exception using errcode='22023',message='practitioner_review_note_required'; end if; update clinical_core.program_versions set status=case when _operation='approve_program_version' then 'approved' else 'returned' end,review_note=btrim(_args->>'_note'),approved_by_person_id=case when _operation='approve_program_version' then _actor end,approved_at=case when _operation='approve_program_version' then clock_timestamp() end where id=(_args->>'_version_id')::uuid and organization_id=_org and status='in_review' returning id into _id; if not found then raise exception using errcode='40001',message='program_review_refused'; end if; return jsonb_build_object('ok',true);
  elsif _operation='publish_program_version' then update clinical_core.program_versions set status='published',published_at=clock_timestamp() where id=(_args->>'_version_id')::uuid and organization_id=_org and status='approved' returning program_id,id into _id2,_id; if not found then raise exception using errcode='40001',message='approved_program_required'; end if; update clinical_core.program_versions set status='superseded' where program_id=_id2 and id<>_id and status='published'; update clinical_core.programs set status='active',active_version_id=_id,updated_at=clock_timestamp() where id=_id2; return jsonb_build_object('ok',true,'versionId',_id);
  elsif _operation='revise_program_version' then select * into _pv from clinical_core.program_versions where id=(_args->>'_version_id')::uuid and organization_id=_org and status in('approved','published'); if not found then raise exception using errcode='P0002',message='program_version_not_revisable'; end if; select max(version)+1 into _version from clinical_core.program_versions where program_id=_pv.program_id; insert into clinical_core.program_versions(organization_id,program_id,version,content,content_sha256,created_by_person_id) values(_org,_pv.program_id,_version,_pv.content,_pv.content_sha256,_actor) returning id into _id; return jsonb_build_object('versionId',_id,'version',_version);
  elsif _operation='archive_program' then update clinical_core.programs set status=case when (_args->>'_archived')::boolean then 'archived' else 'draft' end,archived_at=case when (_args->>'_archived')::boolean then clock_timestamp() end,updated_at=clock_timestamp() where id=(_args->>'_program_id')::uuid and organization_id=_org returning id into _id; if not found then raise exception using errcode='P0002',message='program_not_found'; end if; return jsonb_build_object('ok',true);
  elsif _operation='upsert_program_offer' then _id:=nullif(_args->>'_offer_id','')::uuid; if _id is null then insert into clinical_core.program_offers(organization_id,program_id,name,payment_mode,price_cents,currency,access_duration_days,enrollment_open,status) values(_org,(_args->>'_program_id')::uuid,btrim(_args->>'_name'),_args->>'_payment_mode',(_args->>'_price_cents')::integer,lower(_args->>'_currency'),nullif(_args->>'_access_duration_days','')::integer,(_args->>'_enrollment_open')::boolean,_args->>'_status') returning id into _id; else update clinical_core.program_offers set name=btrim(_args->>'_name'),payment_mode=_args->>'_payment_mode',price_cents=(_args->>'_price_cents')::integer,currency=lower(_args->>'_currency'),access_duration_days=nullif(_args->>'_access_duration_days','')::integer,enrollment_open=(_args->>'_enrollment_open')::boolean,status=_args->>'_status',version=version+1,updated_at=clock_timestamp() where id=_id and organization_id=_org and program_id=(_args->>'_program_id')::uuid; end if; if not found and _id is not null then raise exception using errcode='P0002',message='program_offer_not_found'; end if; return jsonb_build_object('offerId',_id);
  elsif _operation='enroll_patient_in_program' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); select * into _program from clinical_core.programs where id=(_args->>'_program_id')::uuid and organization_id=_org and status='active' and active_version_id is not null; if not found then raise exception using errcode='P0002',message='published_program_not_found'; end if; select * into _offer from clinical_core.program_offers where id=(_args->>'_offer_id')::uuid and organization_id=_org and program_id=_program.id and status='active' and enrollment_open; if not found then raise exception using errcode='P0002',message='open_program_offer_not_found'; end if; if _offer.payment_mode<>'complimentary' then raise exception using errcode='55000',message='program_paid_enrollment_requires_paid_invoice'; end if; if length(btrim(coalesce(_args->>'_comp_reason','')))<10 then raise exception using errcode='22023',message='complimentary_reason_required'; end if; insert into clinical_core.program_enrollments(organization_id,patient_record_id,program_id,program_version_id,offer_id,status,access_expires_at,complimentary_reason_present,enrolled_by_person_id) values(_org,_patient,_program.id,_program.active_version_id,_offer.id,case when (_args->>'_activate')::boolean then 'active' else 'pending' end,case when _offer.access_duration_days is null then null else clock_timestamp()+make_interval(days=>_offer.access_duration_days) end,true,_actor) returning id into _id; return jsonb_build_object('enrollmentId',_id,'status',case when (_args->>'_activate')::boolean then 'active' else 'pending' end);
  elsif _operation='get_patient_programs' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); select coalesce(jsonb_agg(to_jsonb(e) order by e.enrolled_at desc),'[]'::jsonb) into _rows from clinical_core.program_enrollments e where organization_id=_org and patient_record_id=_patient; return _rows;
  elsif _operation='set_program_enrollment_status' then update clinical_core.program_enrollments set status=_args->>'_status',version=version+1,updated_at=clock_timestamp() where id=(_args->>'_enrollment_id')::uuid and organization_id=_org returning version into _version; if not found or ((_args->>'_status') in ('withdrawn') and length(btrim(coalesce(_args->>'_reason','')))<10) then raise exception using errcode='22023',message='enrollment_transition_invalid'; end if; return jsonb_build_object('ok',true,'version',_version);
  elsif _operation='record_program_progress' then select * into _enrollment from clinical_core.program_enrollments where id=(_args->>'_enrollment_id')::uuid and organization_id=_org and status='active'; if not found then raise exception using errcode='P0002',message='active_enrollment_not_found'; end if; perform clinical_private.require_clinical_patient(_org,_enrollment.patient_record_id); insert into clinical_core.program_progress(organization_id,enrollment_id,lesson_id,block_id,kind,payload,needs_review,recorded_by_person_id) values(_org,_enrollment.id,nullif(_args->>'_lesson_id',''),nullif(_args->>'_block_id',''),_args->>'_kind',_args->'_payload',(_args->>'_needs_review')::boolean,_actor) returning id into _id; return jsonb_build_object('progressId',_id,'reviewState','unreviewed');
  elsif _operation='review_program_progress' then update clinical_core.program_progress set review_state='reviewed',reviewed_by_person_id=_actor,reviewed_at=clock_timestamp() where id=(_args->>'_progress_id')::uuid and organization_id=_org and review_state='unreviewed' returning id into _id; if not found then raise exception using errcode='40001',message='progress_review_refused'; end if; return jsonb_build_object('ok',true);
  else raise exception using errcode='0A000',message='program_operation_not_supported'; end if;
end $$;
revoke all on function clinical_core.invoke_program_operation(text,jsonb) from public;
grant execute on function clinical_core.invoke_program_operation(text,jsonb) to clinical_core_api;
