-- AWS-native packages, memberships, entitlements, and reconciliation.
-- No plans or patient benefits are seeded. Benefits are granted only from a
-- paid AWS invoice or a documented complimentary assignment.

create table clinical_core.billing_plans (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  plan_type text not null check(plan_type in('package','membership')), name text not null, description text, kind text,
  version integer not null default 1, archived_at timestamptz, created_by_person_id uuid not null references clinical_core.persons(id),
  created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(), unique(id,organization_id)
);
create table clinical_core.billing_plan_versions (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  plan_id uuid not null, plan_type text not null check(plan_type in('package','membership')), version_number integer not null,
  status text not null default 'draft' check(status in('draft','published','superseded')), currency text not null default 'usd', price_minor bigint not null check(price_minor>=0),
  terms_summary text not null, terms jsonb not null default '{}'::jsonb check(jsonb_typeof(terms)='object'), published_at timestamptz,
  created_by_person_id uuid not null references clinical_core.persons(id), created_at timestamptz not null default clock_timestamp(),
  foreign key(plan_id,organization_id) references clinical_core.billing_plans(id,organization_id), unique(plan_id,version_number), unique(id,organization_id)
);
create table clinical_core.plan_acceptances (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  patient_record_id uuid not null references clinical_core.patient_records(id), plan_version_id uuid not null references clinical_core.billing_plan_versions(id),
  invoice_id uuid references clinical_core.billing_invoices(id), method text not null, terms_snapshot jsonb not null,
  recorded_by_person_id uuid not null references clinical_core.persons(id), recorded_at timestamptz not null default clock_timestamp()
);
create table clinical_core.patient_memberships (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  patient_record_id uuid not null references clinical_core.patient_records(id), plan_version_id uuid not null references clinical_core.billing_plan_versions(id),
  status text not null default 'active' check(status in('trialing','active','paused','canceled','expired')),
  version integer not null default 1, starts_at timestamptz not null default clock_timestamp(), expires_at timestamptz,
  cancel_at_period_end boolean not null default false, lifecycle_reason text, updated_at timestamptz not null default clock_timestamp(), unique(id,organization_id)
);
create table clinical_core.entitlements (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  patient_record_id uuid not null references clinical_core.patient_records(id), plan_version_id uuid not null references clinical_core.billing_plan_versions(id),
  source text not null check(source in('package_purchase','complimentary','membership')), source_invoice_id uuid references clinical_core.billing_invoices(id),
  credit_mode text not null, granted_quantity integer not null check(granted_quantity>0), remaining_quantity integer not null,
  reserved_quantity integer not null default 0, consumed_quantity integer not null default 0, expired_quantity integer not null default 0,
  refunded_quantity integer not null default 0, restrictions jsonb not null default '{}'::jsonb, status text not null default 'active', expires_at timestamptz,
  created_by_person_id uuid not null references clinical_core.persons(id), created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(),
  unique(source_invoice_id,plan_version_id), unique(id,organization_id),
  check(granted_quantity=remaining_quantity+reserved_quantity+consumed_quantity+expired_quantity+refunded_quantity),
  check(remaining_quantity>=0 and reserved_quantity>=0 and consumed_quantity>=0 and expired_quantity>=0 and refunded_quantity>=0)
);
create table clinical_core.entitlement_ledger (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  entitlement_id uuid not null references clinical_core.entitlements(id), kind text not null, quantity integer not null check(quantity>0),
  ref_type text not null, ref_id uuid, reason_present boolean not null, actor_person_id uuid not null references clinical_core.persons(id),
  occurred_at timestamptz not null default clock_timestamp()
);
create table clinical_core.entitlement_reservations (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  entitlement_id uuid not null references clinical_core.entitlements(id), appointment_id uuid not null references clinical_core.appointments(id),
  quantity integer not null check(quantity>0), state text not null default 'reserved' check(state in('reserved','consumed','released','review_required')),
  created_at timestamptz not null default clock_timestamp(), settled_at timestamptz, unique(entitlement_id,appointment_id)
);
create table clinical_core.org_billing_policies (
  organization_id uuid primary key references clinical_core.organizations(id), consume_on text not null check(consume_on in('arrived','completed')),
  late_cancel_policy text not null check(late_cancel_policy in('consume','release','review')),
  late_cancel_window_hours integer not null check(late_cancel_window_hours between 0 and 720),
  no_show_policy text not null check(no_show_policy in('consume','release','review')), updated_by_person_id uuid not null references clinical_core.persons(id),
  updated_at timestamptz not null default clock_timestamp()
);
create table clinical_core.reconciliation_exceptions (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  ref_type text not null, ref_id uuid not null, status text not null default 'open' check(status in('open','resolved','dismissed')),
  reason_code text not null, version integer not null default 1, resolution text, resolution_reason text,
  resolved_by_person_id uuid references clinical_core.persons(id), resolved_at timestamptz, created_at timestamptz not null default clock_timestamp(), unique(id,organization_id)
);
create table clinical_core.plan_events (
  id uuid primary key default public.gen_random_uuid(), organization_id uuid not null references clinical_core.organizations(id),
  action text not null, entity_type text not null, entity_id uuid, safe_metadata jsonb not null default '{}'::jsonb,
  actor_person_id uuid not null references clinical_core.persons(id), occurred_at timestamptz not null default clock_timestamp(),
  check(jsonb_typeof(safe_metadata)='object' and not(safe_metadata ?| array['reason','terms','patient','description']))
);

do $$ declare _table text; begin foreach _table in array array['billing_plans','billing_plan_versions','plan_acceptances','patient_memberships','entitlements','entitlement_ledger','entitlement_reservations','org_billing_policies','reconciliation_exceptions','plan_events'] loop execute format('alter table clinical_core.%I enable row level security',_table); execute format('revoke all on clinical_core.%I from public,clinical_core_api',_table); end loop; end $$;
create trigger plan_acceptances_append_only before update or delete on clinical_core.plan_acceptances for each row execute function clinical_reference.reject_immutable_catalog_history();
create trigger entitlement_ledger_append_only before update or delete on clinical_core.entitlement_ledger for each row execute function clinical_reference.reject_immutable_catalog_history();
create trigger plan_events_append_only before update or delete on clinical_core.plan_events for each row execute function clinical_reference.reject_immutable_catalog_history();

create or replace function clinical_private.move_entitlement(_id uuid,_kind text,_quantity integer,_ref_type text,_ref_id uuid,_reason text,_actor uuid)
returns void language plpgsql security definer set search_path='' as $$
declare _e clinical_core.entitlements%rowtype; begin select * into _e from clinical_core.entitlements where id=_id for update; if not found or _quantity<=0 then raise exception using errcode='22023',message='entitlement_move_invalid'; end if;
  if _kind='reserve' and _e.status='active' and (_e.expires_at is null or _e.expires_at>clock_timestamp()) and _e.remaining_quantity>=_quantity then update clinical_core.entitlements set remaining_quantity=remaining_quantity-_quantity,reserved_quantity=reserved_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='release' and _e.reserved_quantity>=_quantity then update clinical_core.entitlements set reserved_quantity=reserved_quantity-_quantity,remaining_quantity=remaining_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='consume' and _e.reserved_quantity>=_quantity then update clinical_core.entitlements set reserved_quantity=reserved_quantity-_quantity,consumed_quantity=consumed_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='expire' and _e.remaining_quantity>=_quantity then update clinical_core.entitlements set remaining_quantity=remaining_quantity-_quantity,expired_quantity=expired_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='refund_revoke' and _e.remaining_quantity>=_quantity then update clinical_core.entitlements set remaining_quantity=remaining_quantity-_quantity,refunded_quantity=refunded_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='manual_restore' and _reason is not null and _e.consumed_quantity>=_quantity then update clinical_core.entitlements set consumed_quantity=consumed_quantity-_quantity,remaining_quantity=remaining_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  elsif _kind='manual_restore' and _reason is not null and _e.expired_quantity>=_quantity then update clinical_core.entitlements set expired_quantity=expired_quantity-_quantity,remaining_quantity=remaining_quantity+_quantity,updated_at=clock_timestamp() where id=_id;
  else raise exception using errcode='40001',message='entitlement_balance_conflict'; end if;
  insert into clinical_core.entitlement_ledger(organization_id,entitlement_id,kind,quantity,ref_type,ref_id,reason_present,actor_person_id) values(_e.organization_id,_id,_kind,_quantity,_ref_type,_ref_id,_reason is not null,_actor);
end $$;

create or replace function clinical_core.invoke_plan_operation(_operation text,_args jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare _org uuid:=clinical_private.organization_id(); _actor uuid; _id uuid; _id2 uuid; _patient uuid; _version integer; _rows jsonb; _count integer:=0; _plan clinical_core.billing_plans%rowtype; _pv clinical_core.billing_plan_versions%rowtype; _ent clinical_core.entitlements%rowtype; _reservation clinical_core.entitlement_reservations%rowtype; _invoice clinical_core.billing_invoices%rowtype; _action text;
begin if _args is null or jsonb_typeof(_args)<>'object' or octet_length(_args::text)>524288 then raise exception using errcode='22023',message='plan_arguments_invalid'; end if; if (_args->>'_organization_id')::uuid<>_org then raise exception using errcode='42501',message='organization_context_mismatch'; end if; _actor:=clinical_private.require_knowledge_editor(_org);
  if _operation='list_plans' then select coalesce(jsonb_agg(to_jsonb(p) order by p.name),'[]'::jsonb) into _rows from clinical_core.billing_plans p where organization_id=_org and ((_args->>'_include_archived')::boolean or archived_at is null); return _rows;
  elsif _operation='upsert_plan' then _id:=nullif(_args->>'_id','')::uuid; if _id is null then insert into clinical_core.billing_plans(organization_id,plan_type,name,description,kind,created_by_person_id) values(_org,_args->>'_plan_type',btrim(_args->>'_name'),nullif(_args->>'_description',''),nullif(_args->>'_kind',''),_actor) returning id,version into _id,_version; else update clinical_core.billing_plans set name=btrim(_args->>'_name'),description=nullif(_args->>'_description',''),kind=nullif(_args->>'_kind',''),archived_at=case when (_args->>'_archive')::boolean then clock_timestamp() end,version=version+1,updated_at=clock_timestamp() where id=_id and organization_id=_org and plan_type=_args->>'_plan_type' and version=(_args->>'_expected_version')::integer returning version into _version; if not found then raise exception using errcode='40001',message='plan_version_conflict'; end if; end if; return jsonb_build_object('id',_id,'version',_version);
  elsif _operation='create_plan_version' then select * into _plan from clinical_core.billing_plans where id=(_args->>'_plan_id')::uuid and organization_id=_org and plan_type=_args->>'_plan_type' and archived_at is null; if not found then raise exception using errcode='P0002',message='plan_not_found'; end if; select coalesce(max(version_number),0)+1 into _version from clinical_core.billing_plan_versions where plan_id=_plan.id; insert into clinical_core.billing_plan_versions(organization_id,plan_id,plan_type,version_number,currency,price_minor,terms_summary,terms,created_by_person_id) values(_org,_plan.id,_plan.plan_type,_version,lower(_args->>'_currency'),(_args->>'_price_minor')::bigint,btrim(_args->>'_terms_summary'),_args-'_organization_id'-'_plan_id'-'_plan_type'-'_price_minor'-'_currency'-'_terms_summary',_actor) returning id into _id; return jsonb_build_object('id',_id,'versionNumber',_version);
  elsif _operation='publish_plan_version' then update clinical_core.billing_plan_versions set status='published',published_at=clock_timestamp() where id=(_args->>'_version_id')::uuid and organization_id=_org and plan_type=_args->>'_plan_type' and status='draft' returning id into _id; if not found then raise exception using errcode='40001',message='plan_publish_refused'; end if; return jsonb_build_object('ok',true,'versionId',_id);
  elsif _operation='purchase_package' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); select * into _pv from clinical_core.billing_plan_versions where id=(_args->>'_package_version_id')::uuid and organization_id=_org and plan_type='package' and status='published'; if not found then raise exception using errcode='P0002',message='published_package_not_found'; end if; insert into clinical_core.billing_invoices(organization_id,patient_record_id,status,currency,lines,subtotal_minor,total_minor,created_by_person_id) values(_org,_patient,'draft',_pv.currency,jsonb_build_array(jsonb_build_object('productId',_pv.plan_id,'name','governed package','quantity',1,'amountMinor',_pv.price_minor,'taxRateBps',0)),_pv.price_minor,_pv.price_minor,_actor) returning id into _id; insert into clinical_core.plan_acceptances(organization_id,patient_record_id,plan_version_id,invoice_id,method,terms_snapshot,recorded_by_person_id) values(_org,_patient,_pv.id,_id,_args->>'_acceptance_method',to_jsonb(_pv),_actor); return jsonb_build_object('invoiceId',_id,'packageVersionId',_pv.id);
  elsif _operation='grant_entitlements_for_invoice' then select * into _invoice from clinical_core.billing_invoices where id=(_args->>'_invoice_id')::uuid and organization_id=_org and status='paid'; if not found then raise exception using errcode='42501',message='paid_invoice_required'; end if; for _pv in select v.* from clinical_core.billing_plan_versions v join clinical_core.plan_acceptances a on a.plan_version_id=v.id where a.invoice_id=_invoice.id and a.organization_id=_org loop insert into clinical_core.entitlements(organization_id,patient_record_id,plan_version_id,source,source_invoice_id,credit_mode,granted_quantity,remaining_quantity,restrictions,expires_at,created_by_person_id) values(_org,_invoice.patient_record_id,_pv.id,'package_purchase',_invoice.id,coalesce(_pv.terms->>'_credit_mode','visit'),coalesce((_pv.terms->>'_credit_quantity')::integer,1),coalesce((_pv.terms->>'_credit_quantity')::integer,1),_pv.terms,case when (_pv.terms->>'_expires_after_days') is null then null else clock_timestamp()+make_interval(days=>(_pv.terms->>'_expires_after_days')::integer) end,_actor) on conflict(source_invoice_id,plan_version_id) do nothing returning id into _id; if _id is not null then insert into clinical_core.entitlement_ledger(organization_id,entitlement_id,kind,quantity,ref_type,ref_id,reason_present,actor_person_id) values(_org,_id,'grant',coalesce((_pv.terms->>'_credit_quantity')::integer,1),'invoice',_invoice.id,true,_actor); _count:=_count+1; _id:=null; end if; end loop; return jsonb_build_object('entitlementsCreated',_count);
  elsif _operation='assign_complimentary_plan' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); if length(btrim(coalesce(_args->>'_reason','')))<10 then raise exception using errcode='22023',message='complimentary_reason_required'; end if; select * into _pv from clinical_core.billing_plan_versions where id=(_args->>'_version_id')::uuid and organization_id=_org and plan_type=_args->>'_plan_type' and status='published'; if not found then raise exception using errcode='P0002',message='published_plan_not_found'; end if; if _pv.plan_type='package' then insert into clinical_core.entitlements(organization_id,patient_record_id,plan_version_id,source,credit_mode,granted_quantity,remaining_quantity,restrictions,expires_at,created_by_person_id) values(_org,_patient,_pv.id,'complimentary',coalesce(_pv.terms->>'_credit_mode','visit'),coalesce((_pv.terms->>'_credit_quantity')::integer,1),coalesce((_pv.terms->>'_credit_quantity')::integer,1),_pv.terms,nullif(_args->>'_expires_at','')::timestamptz,_actor) returning id into _id; insert into clinical_core.entitlement_ledger(organization_id,entitlement_id,kind,quantity,ref_type,reason_present,actor_person_id) values(_org,_id,'grant',coalesce((_pv.terms->>'_credit_quantity')::integer,1),'complimentary',true,_actor); else insert into clinical_core.patient_memberships(organization_id,patient_record_id,plan_version_id,expires_at,lifecycle_reason) values(_org,_patient,_pv.id,nullif(_args->>'_expires_at','')::timestamptz,'documented complimentary assignment') returning id into _id2; end if; return jsonb_build_object('entitlementId',_id,'patientMembershipId',_id2,'complimentary',true);
  elsif _operation='get_patient_entitlements' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); return jsonb_build_object('entitlements',(select coalesce(jsonb_agg(to_jsonb(e)),'[]'::jsonb) from clinical_core.entitlements e where organization_id=_org and patient_record_id=_patient),'memberships',(select coalesce(jsonb_agg(to_jsonb(m)),'[]'::jsonb) from clinical_core.patient_memberships m where organization_id=_org and patient_record_id=_patient));
  elsif _operation='reserve_entitlement_for_appointment' then select * into _ent from clinical_core.entitlements where id=(_args->>'_entitlement_id')::uuid and organization_id=_org; perform clinical_private.require_clinical_patient(_org,_ent.patient_record_id); if not exists(select 1 from clinical_core.appointments where id=(_args->>'_appointment_id')::uuid and organization_id=_org and patient_record_id=_ent.patient_record_id) then raise exception using errcode='42501',message='appointment_patient_mismatch'; end if; perform clinical_private.move_entitlement(_ent.id,'reserve',(_args->>'_quantity')::integer,'appointment',(_args->>'_appointment_id')::uuid,null,_actor); insert into clinical_core.entitlement_reservations(organization_id,entitlement_id,appointment_id,quantity) values(_org,_ent.id,(_args->>'_appointment_id')::uuid,(_args->>'_quantity')::integer) returning id into _id; return jsonb_build_object('reservationId',_id,'state','reserved');
  elsif _operation='settle_entitlement_for_appointment' then select * into _reservation from clinical_core.entitlement_reservations where appointment_id=(_args->>'_appointment_id')::uuid and organization_id=_org and state='reserved' for update; if not found then raise exception using errcode='P0002',message='reservation_not_found'; end if; _action:=case _args->>'_outcome' when 'completed' then 'consume' when 'cancelled' then 'release' when 'arrived' then case coalesce((select consume_on from clinical_core.org_billing_policies where organization_id=_org),'completed') when 'arrived' then 'consume' else null end when 'no_show' then (select no_show_policy from clinical_core.org_billing_policies where organization_id=_org) when 'late_cancel' then (select late_cancel_policy from clinical_core.org_billing_policies where organization_id=_org) end; if _action='review' or _action is null then update clinical_core.entitlement_reservations set state='review_required',settled_at=clock_timestamp() where id=_reservation.id; return jsonb_build_object('state','review_required','reviewRequired',true); end if; perform clinical_private.move_entitlement(_reservation.entitlement_id,_action,_reservation.quantity,'appointment',_reservation.appointment_id,nullif(_args->>'_reason',''),_actor); update clinical_core.entitlement_reservations set state=case when _action='consume' then 'consumed' else 'released' end,settled_at=clock_timestamp() where id=_reservation.id; return jsonb_build_object('state',case when _action='consume' then 'consumed' else 'released' end);
  elsif _operation='restore_entitlement' then perform clinical_private.move_entitlement((_args->>'_entitlement_id')::uuid,'manual_restore',(_args->>'_quantity')::integer,'manual',null,nullif(_args->>'_reason',''),_actor); return jsonb_build_object('ok',true);
  elsif _operation in('expire_entitlements','revoke_entitlements_for_refund') then for _ent in select * from clinical_core.entitlements where organization_id=_org and remaining_quantity>0 and ((_operation='expire_entitlements' and expires_at<=clock_timestamp()) or (_operation='revoke_entitlements_for_refund' and source_invoice_id=(_args->>'_invoice_id')::uuid)) loop perform clinical_private.move_entitlement(_ent.id,case when _operation='expire_entitlements' then 'expire' else 'refund_revoke' end,_ent.remaining_quantity,case when _operation='expire_entitlements' then 'system' else 'invoice' end,case when _operation='expire_entitlements' then null else (_args->>'_invoice_id')::uuid end,nullif(_args->>'_reason',''),_actor); _count:=_count+1; end loop; return jsonb_build_object(case when _operation='expire_entitlements' then 'expired' else 'revoked' end,_count);
  elsif _operation='set_membership_lifecycle' then _action:=_args->>'_action'; update clinical_core.patient_memberships set status=case _action when 'pause' then 'paused' when 'resume' then 'active' when 'cancel_now' then 'canceled' when 'reactivate' then 'active' else status end,cancel_at_period_end=case when _action='cancel_at_period_end' then true when _action='reactivate' then false else cancel_at_period_end end,lifecycle_reason=nullif(_args->>'_reason',''),version=version+1,updated_at=clock_timestamp() where id=(_args->>'_patient_membership_id')::uuid and organization_id=_org and version=(_args->>'_expected_version')::integer returning version into _version; if not found then raise exception using errcode='40001',message='membership_version_conflict'; end if; return jsonb_build_object('ok',true,'version',_version);
  elsif _operation='set_org_billing_policy' then insert into clinical_core.org_billing_policies(organization_id,consume_on,late_cancel_policy,late_cancel_window_hours,no_show_policy,updated_by_person_id) values(_org,_args->>'_consume_on',_args->>'_late_cancel_policy',(_args->>'_late_cancel_window_hours')::integer,_args->>'_no_show_policy',_actor) on conflict(organization_id) do update set consume_on=excluded.consume_on,late_cancel_policy=excluded.late_cancel_policy,late_cancel_window_hours=excluded.late_cancel_window_hours,no_show_policy=excluded.no_show_policy,updated_by_person_id=excluded.updated_by_person_id,updated_at=clock_timestamp(); return jsonb_build_object('ok',true);
  elsif _operation='get_reconciliation_workspace' then select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc),'[]'::jsonb) into _rows from clinical_core.reconciliation_exceptions r where organization_id=_org and (nullif(_args->>'_status','') is null or status=_args->>'_status'); return _rows;
  elsif _operation='resolve_reconciliation_exception' then update clinical_core.reconciliation_exceptions set status=_args->>'_resolution',resolution=_args->>'_resolution',resolution_reason=btrim(_args->>'_reason'),resolved_by_person_id=_actor,resolved_at=clock_timestamp(),version=version+1 where id=(_args->>'_exception_id')::uuid and organization_id=_org and version=(_args->>'_expected_version')::integer returning version into _version; if not found then raise exception using errcode='40001',message='reconciliation_version_conflict'; end if; return jsonb_build_object('ok',true,'version',_version);
  else raise exception using errcode='0A000',message='plan_operation_not_supported'; end if;
end $$;
revoke all on function clinical_core.invoke_plan_operation(text,jsonb) from public;
grant execute on function clinical_core.invoke_plan_operation(text,jsonb) to clinical_core_api;
