-- AWS-native clinical inbox and communication preference boundary.
-- Drafting is supported; delivery is a durable refusal until an independently
-- approved messaging provider is registered. No message is ever marked sent
-- based only on a UI request.

create table clinical_core.communication_preferences(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),patient_record_id uuid not null references clinical_core.patient_records(id),preferred_channel text not null check(preferred_channel in('none','alp_in_app','email','sms','push')),email_ok boolean not null default false,sms_ok boolean not null default false,push_ok boolean not null default false,do_not_contact boolean not null default false,consent_artifact_id uuid references clinical_core.consent_artifacts(id),note_present boolean not null default false,version integer not null default 1,updated_by_person_id uuid not null references clinical_core.persons(id),updated_at timestamptz not null default clock_timestamp(),unique(organization_id,patient_record_id),unique(id,organization_id));
create table clinical_core.conversations(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),patient_record_id uuid not null references clinical_core.patient_records(id),subject text not null,category text not null,priority text not null check(priority in('low','medium','high','urgent')),status text not null default 'open' check(status in('open','waiting','closed','archived')),queue text not null default 'clinical',assigned_person_id uuid references clinical_core.persons(id),due_at timestamptz,version integer not null default 1,last_message_at timestamptz,created_by_person_id uuid not null references clinical_core.persons(id),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(id,organization_id));
create table clinical_core.messages(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),conversation_id uuid not null references clinical_core.conversations(id),sender_person_id uuid not null references clinical_core.persons(id),body text not null check(char_length(body) between 1 and 65536),status text not null default 'draft' check(status in('draft','cancelled','queued','sent','failed')),channel text,version integer not null default 1,idempotency_key text,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(organization_id,idempotency_key),unique(id,organization_id));
create table clinical_core.message_draft_revisions(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),message_id uuid not null references clinical_core.messages(id),version integer not null,body_sha256 text not null check(body_sha256~'^[0-9a-f]{64}$'),author_person_id uuid not null references clinical_core.persons(id),created_at timestamptz not null default clock_timestamp(),unique(message_id,version));
create table clinical_core.message_attachments(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),conversation_id uuid not null references clinical_core.conversations(id),message_id uuid not null references clinical_core.messages(id),file_name text not null,content_type text not null,byte_size bigint not null check(byte_size between 1 and 26214400),sha256 text not null check(sha256~'^[0-9a-f]{64}$'),storage_state text not null default 'registration_only' check(storage_state in('registration_only','quarantined','verified')),created_by_person_id uuid not null references clinical_core.persons(id),created_at timestamptz not null default clock_timestamp());
create table clinical_core.conversation_reads(organization_id uuid not null references clinical_core.organizations(id),conversation_id uuid not null references clinical_core.conversations(id),person_id uuid not null references clinical_core.persons(id),last_read_at timestamptz not null default clock_timestamp(),primary key(conversation_id,person_id));
create table clinical_core.messaging_provider_registrations(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),channel text not null,provider_key text not null,review_state text not null default 'pending_review' check(review_state in('pending_review','approved','rejected')),enabled boolean not null default false check(enabled=false),created_at timestamptz not null default clock_timestamp(),unique(organization_id,channel));
create table clinical_core.message_outbox(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),message_id uuid not null references clinical_core.messages(id),channel text not null,provider_key text not null,status text not null default 'queued' check(status in('queued','claimed','delivered','failed')),idempotency_key text not null,created_at timestamptz not null default clock_timestamp(),unique(organization_id,idempotency_key));
create table clinical_core.message_ai_reviews(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),conversation_id uuid not null references clinical_core.conversations(id),suggestion_sha256 text not null check(suggestion_sha256~'^[0-9a-f]{64}$'),decision text not null check(decision in('accepted','rejected','edited')),reviewed_by_person_id uuid not null references clinical_core.persons(id),reviewed_at timestamptz not null default clock_timestamp());
create table clinical_core.conversation_events(id uuid primary key default public.gen_random_uuid(),organization_id uuid not null references clinical_core.organizations(id),conversation_id uuid not null references clinical_core.conversations(id),message_id uuid references clinical_core.messages(id),action text not null,safe_metadata jsonb not null default '{}'::jsonb,actor_person_id uuid not null references clinical_core.persons(id),occurred_at timestamptz not null default clock_timestamp(),check(jsonb_typeof(safe_metadata)='object' and not(safe_metadata ?| array['body','subject','note','fileName'])));

do $$ declare _table text; begin foreach _table in array array['communication_preferences','conversations','messages','message_draft_revisions','message_attachments','conversation_reads','messaging_provider_registrations','message_outbox','message_ai_reviews','conversation_events'] loop execute format('alter table clinical_core.%I enable row level security',_table); execute format('revoke all on clinical_core.%I from public,clinical_core_api',_table); end loop; end $$;
create trigger message_draft_revisions_append_only before update or delete on clinical_core.message_draft_revisions for each row execute function clinical_reference.reject_immutable_catalog_history();
create trigger message_ai_reviews_append_only before update or delete on clinical_core.message_ai_reviews for each row execute function clinical_reference.reject_immutable_catalog_history();
create trigger conversation_events_append_only before update or delete on clinical_core.conversation_events for each row execute function clinical_reference.reject_immutable_catalog_history();

create or replace function clinical_core.invoke_inbox_operation(_operation text,_args jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare _org uuid:=clinical_private.organization_id(); _actor uuid; _id uuid; _patient uuid; _version integer; _rows jsonb; _conversation clinical_core.conversations%rowtype; _message clinical_core.messages%rowtype; _prefs clinical_core.communication_preferences%rowtype; _provider clinical_core.messaging_provider_registrations%rowtype; _note clinical_core.clinical_notes%rowtype; _hash text;
begin if _args is null or jsonb_typeof(_args)<>'object' or octet_length(_args::text)>524288 then raise exception using errcode='22023',message='inbox_arguments_invalid'; end if; if _args ? '_organization_id' and (_args->>'_organization_id')::uuid<>_org then raise exception using errcode='42501',message='organization_context_mismatch'; end if; _actor:=clinical_private.require_knowledge_editor(_org);
  if _operation='create_conversation' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); insert into clinical_core.conversations(organization_id,patient_record_id,subject,category,priority,created_by_person_id) values(_org,_patient,btrim(_args->>'_subject'),_args->>'_category',_args->>'_priority',_actor) returning id into _id; return jsonb_build_object('conversationId',_id,'status','open');
  elsif _operation='list_inbox' then select coalesce(jsonb_agg(to_jsonb(c) order by c.updated_at desc),'[]'::jsonb) into _rows from (select * from clinical_core.conversations where organization_id=_org and (nullif(_args->>'_status','') is null or status=_args->>'_status') and (nullif(_args->>'_category','') is null or category=_args->>'_category') and (nullif(_args->>'_priority','') is null or priority=_args->>'_priority') and (nullif(_args->>'_queue','') is null or queue=_args->>'_queue') and (not (_args->>'_assigned_to_me')::boolean or assigned_person_id=_actor) and (not (_args->>'_due_only')::boolean or due_at<=clock_timestamp()) and (nullif(_args->>'_query','') is null or subject ilike '%'||(_args->>'_query')||'%') order by updated_at desc limit least(coalesce((_args->>'_limit')::integer,100),500)) c; return _rows;
  elsif _operation='get_conversation' then select * into _conversation from clinical_core.conversations where id=(_args->>'_conversation_id')::uuid and organization_id=_org; if not found then raise exception using errcode='P0002',message='conversation_not_found'; end if; perform clinical_private.require_clinical_patient(_org,_conversation.patient_record_id); return jsonb_build_object('conversation',to_jsonb(_conversation),'messages',(select coalesce(jsonb_agg(to_jsonb(m) order by created_at),'[]'::jsonb) from clinical_core.messages m where conversation_id=_conversation.id));
  elsif _operation='get_patient_messages' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); select coalesce(jsonb_agg(to_jsonb(c) order by c.updated_at desc),'[]'::jsonb) into _rows from clinical_core.conversations c where organization_id=_org and patient_record_id=_patient; return _rows;
  elsif _operation='get_inbox_today_summary' then return jsonb_build_object('open',(select count(*) from clinical_core.conversations where organization_id=_org and status='open'),'urgent',(select count(*) from clinical_core.conversations where organization_id=_org and status='open' and priority='urgent'),'dueToday',(select count(*) from clinical_core.conversations where organization_id=_org and status='open' and due_at::date=current_date),'unread',(select count(*) from clinical_core.conversations c where organization_id=_org and not exists(select 1 from clinical_core.conversation_reads r where r.conversation_id=c.id and r.person_id=_actor and r.last_read_at>=coalesce(c.last_message_at,c.created_at))));
  elsif _operation='save_message_draft' then select * into _conversation from clinical_core.conversations where id=(_args->>'_conversation_id')::uuid and organization_id=_org; perform clinical_private.require_clinical_patient(_org,_conversation.patient_record_id); _id:=nullif(_args->>'_message_id','')::uuid; if _id is null then insert into clinical_core.messages(organization_id,conversation_id,sender_person_id,body) values(_org,_conversation.id,_actor,btrim(_args->>'_body')) returning id,version into _id,_version; else update clinical_core.messages set body=btrim(_args->>'_body'),version=version+1,updated_at=clock_timestamp() where id=_id and conversation_id=_conversation.id and sender_person_id=_actor and status='draft' and version=(_args->>'_expected_version')::integer returning version into _version; if not found then raise exception using errcode='40001',message='message_draft_conflict'; end if; end if; _hash:=encode(public.digest(convert_to(btrim(_args->>'_body'),'UTF8'),'sha256'),'hex'); insert into clinical_core.message_draft_revisions(organization_id,message_id,version,body_sha256,author_person_id) values(_org,_id,_version,_hash,_actor); return jsonb_build_object('messageId',_id,'version',_version,'status','draft');
  elsif _operation='cancel_message_draft' then update clinical_core.messages set status='cancelled',version=version+1,updated_at=clock_timestamp() where id=(_args->>'_message_id')::uuid and organization_id=_org and sender_person_id=_actor and status='draft' returning id into _id; if not found then raise exception using errcode='40001',message='message_cancel_refused'; end if; return jsonb_build_object('ok',true,'messageId',_id);
  elsif _operation='register_message_attachment' then select * into _message from clinical_core.messages where id=(_args->>'_message_id')::uuid and conversation_id=(_args->>'_conversation_id')::uuid and organization_id=_org and status='draft'; if not found then raise exception using errcode='P0002',message='draft_message_not_found'; end if; insert into clinical_core.message_attachments(organization_id,conversation_id,message_id,file_name,content_type,byte_size,sha256,created_by_person_id) values(_org,_message.conversation_id,_message.id,btrim(_args->>'_file_name'),lower(_args->>'_content_type'),(_args->>'_byte_size')::bigint,lower(_args->>'_sha256'),_actor) returning id into _id; return jsonb_build_object('attachmentId',_id,'storageState','registration_only','uploadAvailable',false);
  elsif _operation='send_message' then select * into _message from clinical_core.messages where id=(_args->>'_message_id')::uuid and organization_id=_org and sender_person_id=_actor for update; if not found or _message.status<>'draft' then raise exception using errcode='40001',message='draft_message_required'; end if; select * into _conversation from clinical_core.conversations where id=_message.conversation_id; select * into _prefs from clinical_core.communication_preferences where organization_id=_org and patient_record_id=_conversation.patient_record_id; if not found or _prefs.do_not_contact or _prefs.preferred_channel='none' or ((_args->>'_channel')='email' and not _prefs.email_ok) or ((_args->>'_channel')='sms' and not _prefs.sms_ok) or ((_args->>'_channel')='push' and not _prefs.push_ok) then raise exception using errcode='22023',message='communication_consent_required'; end if; select * into _provider from clinical_core.messaging_provider_registrations where organization_id=_org and channel=_args->>'_channel' and review_state='approved' and enabled; if not found then insert into clinical_core.conversation_events(organization_id,conversation_id,message_id,action,safe_metadata,actor_person_id) values(_org,_conversation.id,_message.id,'send_refused',jsonb_build_object('channel',_args->>'_channel','refusal','provider_not_configured'),_actor); return jsonb_build_object('ok',false,'sent',false,'refusal','provider_not_configured','messageId',_message.id,'status','draft'); end if; insert into clinical_core.message_outbox(organization_id,message_id,channel,provider_key,idempotency_key) values(_org,_message.id,_args->>'_channel',_provider.provider_key,coalesce(nullif(_args->>'_idempotency_key',''),_message.id::text||':'||(_args->>'_channel'))) on conflict(organization_id,idempotency_key) do nothing; update clinical_core.messages set status='queued',channel=_args->>'_channel',idempotency_key=coalesce(nullif(_args->>'_idempotency_key',''),_message.id::text||':'||(_args->>'_channel')),version=version+1,updated_at=clock_timestamp() where id=_message.id; return jsonb_build_object('ok',true,'sent',false,'status','queued','messageId',_message.id);
  elsif _operation='mark_conversation_read' then insert into clinical_core.conversation_reads(organization_id,conversation_id,person_id) select _org,id,_actor from clinical_core.conversations where id=(_args->>'_conversation_id')::uuid and organization_id=_org on conflict(conversation_id,person_id) do update set last_read_at=clock_timestamp(); if not found then raise exception using errcode='P0002',message='conversation_not_found'; end if; return jsonb_build_object('ok',true);
  elsif _operation='update_conversation_workflow' then _id:=(_args->>'_conversation_id')::uuid; if (_args->>'_action')='status' then update clinical_core.conversations set status=_args->>'_value',version=version+1,updated_at=clock_timestamp() where id=_id and organization_id=_org and version=(_args->>'_expected_version')::integer returning version into _version; elsif (_args->>'_action')='assign' then update clinical_core.conversations set assigned_person_id=nullif(_args->>'_value','')::uuid,version=version+1,updated_at=clock_timestamp() where id=_id and organization_id=_org and version=(_args->>'_expected_version')::integer returning version into _version; elsif (_args->>'_action')='due' then update clinical_core.conversations set due_at=nullif(_args->>'_at','')::timestamptz,version=version+1,updated_at=clock_timestamp() where id=_id and organization_id=_org and version=(_args->>'_expected_version')::integer returning version into _version; else raise exception using errcode='22023',message='workflow_action_invalid'; end if; if not found then raise exception using errcode='40001',message='conversation_version_conflict'; end if; return jsonb_build_object('ok',true,'version',_version);
  elsif _operation='set_communication_preferences' then _patient:=(_args->>'_patient_id')::uuid; perform clinical_private.require_clinical_patient(_org,_patient); insert into clinical_core.communication_preferences(organization_id,patient_record_id,preferred_channel,email_ok,sms_ok,push_ok,do_not_contact,consent_artifact_id,note_present,updated_by_person_id) values(_org,_patient,_args->>'_preferred_channel',(_args->>'_email_ok')::boolean,(_args->>'_sms_ok')::boolean,(_args->>'_push_ok')::boolean,(_args->>'_do_not_contact')::boolean,nullif(_args->>'_consent_id','')::uuid,nullif(_args->>'_note','') is not null,_actor) on conflict(organization_id,patient_record_id) do update set preferred_channel=excluded.preferred_channel,email_ok=excluded.email_ok,sms_ok=excluded.sms_ok,push_ok=excluded.push_ok,do_not_contact=excluded.do_not_contact,consent_artifact_id=excluded.consent_artifact_id,note_present=excluded.note_present,version=clinical_core.communication_preferences.version+1,updated_by_person_id=_actor,updated_at=clock_timestamp() returning version into _version; return jsonb_build_object('ok',true,'version',_version);
  elsif _operation='review_ai_suggestion' then if (_args->>'_decision') not in('accepted','rejected','edited') then raise exception using errcode='22023',message='suggestion_decision_invalid'; end if; select * into _conversation from clinical_core.conversations where id=(select conversation_id from clinical_core.messages where id=(_args->>'_review_id')::uuid and organization_id=_org); if not found then raise exception using errcode='P0002',message='suggestion_not_found'; end if; insert into clinical_core.message_ai_reviews(organization_id,conversation_id,suggestion_sha256,decision,reviewed_by_person_id) values(_org,_conversation.id,encode(public.digest(convert_to((_args->>'_review_id'),'UTF8'),'sha256'),'hex'),_args->>'_decision',_actor) returning id into _id; return jsonb_build_object('reviewId',_id,'decision',_args->>'_decision');
  elsif _operation='create_task_from_message' then select * into _message from clinical_core.messages where id=(_args->>'_message_id')::uuid and organization_id=_org; select * into _conversation from clinical_core.conversations where id=_message.conversation_id; insert into clinical_core.review_queue_items(organization_id,patient_record_id,item_type,reference_id,title,priority,created_by_person_id,updated_by_person_id) values(_org,_conversation.patient_record_id,'patient_message',_message.id,btrim(_args->>'_title'),_args->>'_priority',_actor,_actor) returning id into _id; return jsonb_build_object('taskId',_id);
  elsif _operation='append_message_to_note' then select * into _message from clinical_core.messages where id=(_args->>'_message_id')::uuid and organization_id=_org and status<>'cancelled'; select * into _note from clinical_core.clinical_notes where encounter_id=(_args->>'_encounter_id')::uuid and organization_id=_org; if not found then raise exception using errcode='P0002',message='encounter_note_not_found'; end if; insert into clinical_core.note_addenda(note_id,referenced_version,author_person_id,reason,content) values(_note.id,_note.current_version,_actor,'Patient message appended to '||btrim(_args->>'_section'),_message.body) returning id into _id; return jsonb_build_object('addendumId',_id,'noteId',_note.id);
  else raise exception using errcode='0A000',message='inbox_operation_not_supported'; end if;
end $$;
revoke all on function clinical_core.invoke_inbox_operation(text,jsonb) from public;
grant execute on function clinical_core.invoke_inbox_operation(text,jsonb) to clinical_core_api;
