if (typeof window !== "undefined") {
  throw new Error("This module is server-only and must not run in the browser.");
}
import { trpcMutation, trpcQuery } from "./trpc.server";
import { resolveOrgId } from "./config";
import type { LiveAuditEvent, LiveTaskResult } from "./live-types";
import { getClinicalAccessToken } from "./session.server";
import { clinicalRpc } from "./supabase-rest.server";

/**
 * Live `actions` namespace (server-only).
 *
 * The persistent audit + downstream-task write path. Backed by the tRPC
 * backend's `clinical.actions.*` procedures, which call the append-only
 * `record_audit_event` / `create_review_task` SECURITY DEFINER RPCs
 * (migration 0013) as the authenticated practitioner. Callers pass only
 * PHI-safe safe_message + metadata; the RPCs stamp actor ids server-side.
 */

/**
 * Registry-shaped audit submission (P0): the browser names a REGISTERED event
 * type; the stored action, resource type, and display text are generated by
 * the backend's server-owned registry. Free-form messages/metadata are
 * rejected there and never leave this app either.
 */
export interface RecordAuditInput {
  eventType: string;
  resourceId?: string;
  patientId?: string;
  metadata?: Record<string, string | number | boolean>;
  organizationId?: string;
}

export const actionsLive = {
  recordAudit(input: RecordAuditInput, sessionToken?: string | null): Promise<{ id: string }> {
    return trpcMutation<{ id: string }>("clinical.actions.recordAudit", {
      organizationId: resolveOrgId(input.organizationId),
      eventType: input.eventType,
      resourceId: input.resourceId ?? null,
      patientId: input.patientId ?? null,
      metadata: input.metadata ?? {},
    }, sessionToken);
  },

  listAuditEvents(
    organizationId?: string,
    limit = 50,
    sessionToken?: string | null,
  ): Promise<LiveAuditEvent[]> {
    return trpcQuery<LiveAuditEvent[]>("clinical.actions.listAuditEvents", {
      organizationId: resolveOrgId(organizationId),
      limit,
    }, sessionToken);
  },

  async createReviewTask(input: {
    patientId: string;
    title: string;
    itemType?: string;
    priority?: "low" | "medium" | "high";
    refId?: string;
  }, sessionToken?: string | null): Promise<LiveTaskResult> {
    const token = await getClinicalAccessToken(sessionToken);
    const result = await clinicalRpc<{
      id: string;
      status: string;
    }>("create_review_task", {
      _patient_id: input.patientId,
      _title: input.title,
      _item_type: input.itemType ?? "abnormal_result",
      _priority: input.priority ?? "medium",
      _ref_id: input.refId ?? null,
    }, token);
    return {
      ok: true,
      id: result.id,
      status: result.status,
      message: "Review task created.",
    };
  },
};
