if (typeof window !== "undefined") {
  throw new Error("This module is server-only and must not run in the browser.");
}
import { resolveOrgId } from "./config";
import type { LiveAuditEvent, LiveTaskResult } from "./live-types";
import { getClinicalAccessToken } from "./session.server";
import { clinicalRpc } from "./aws-clinical-data.server";

/**
 * Live `actions` namespace (server-only).
 *
 * Persistent audit reads, registered generic audit writes, and downstream
 * review-task writes go directly to the clinical Supabase project as the
 * authenticated practitioner. Domain mutations still append their own audit
 * event atomically inside their database function.
 */

/**
 * Registry-shaped audit submission (P0): the browser names a REGISTERED event
 * type; the stored action, resource type, and display text are generated by
 * the database-owned registry. Free-form messages and unregistered metadata
 * are rejected at the database boundary.
 */
export interface RecordAuditInput {
  eventType: string;
  resourceId?: string;
  patientId?: string;
  metadata?: Record<string, string | number | boolean>;
  organizationId?: string;
}

interface AuditEventRow {
  id: string;
  action: string;
  resource_type: string | null;
  resource_id: string | null;
  safe_message: string | null;
  patient_id: string | null;
  actor_user_id: string | null;
  occurred_at: string;
  metadata: Record<string, unknown> | null;
}

export const actionsLive = {
  async recordAudit(
    input: RecordAuditInput,
    sessionToken?: string | null,
  ): Promise<{ id: string }> {
    const token = await getClinicalAccessToken(sessionToken);
    const id = await clinicalRpc<string>("record_registered_audit_event", {
      _organization_id: resolveOrgId(input.organizationId),
      _event_type: input.eventType,
      _resource_id: input.resourceId ?? null,
      _patient_id: input.patientId ?? null,
      _metadata: input.metadata ?? {},
    }, token);
    return { id };
  },

  async listAuditEvents(
    organizationId?: string,
    limit = 50,
    sessionToken?: string | null,
  ): Promise<LiveAuditEvent[]> {
    const token = await getClinicalAccessToken(sessionToken);
    const rows = await clinicalRpc<AuditEventRow[]>("list_audit_events", {
      _organization_id: resolveOrgId(organizationId),
      _limit: Math.min(Math.max(limit, 1), 200),
    }, token);
    return rows.map((row) => ({
      id: row.id,
      action: row.action,
      resourceType: row.resource_type,
      resourceId: row.resource_id,
      safeMessage: row.safe_message,
      patientId: row.patient_id,
      actorUserId: row.actor_user_id,
      occurredAt: row.occurred_at,
      metadata: row.metadata ?? {},
    }));
  },

  async createReviewTask(input: {
    patientId: string;
    title: string;
    itemType?: string;
    priority?: "low" | "medium" | "high";
    refId?: string;
  }, sessionToken?: string | null): Promise<LiveTaskResult> {
    const token = await getClinicalAccessToken(sessionToken);
    const result = await clinicalRpc<{
      id: string;
      status: string;
    }>("create_review_task", {
      _patient_id: input.patientId,
      _title: input.title,
      _item_type: input.itemType ?? "abnormal_result",
      _priority: input.priority ?? "medium",
      _ref_id: input.refId ?? null,
    }, token);
    return {
      ok: true,
      id: result.id,
      status: result.status,
      message: "Review task created.",
    };
  },
};
